# セミコロンを付けない（JS/TS の話なので Markdown にはあまり影響なし）
semi: false

# 文字列はシングルクォート（これも主に JS/TS 用）
singleQuote: true

# 1 行の最大幅
# Markdown の proseWrap を preserve にしているので、
# 主にコードブロックやオブジェクトリテラルに効きます
printWidth: 100

# インデント
tabWidth: 2
useTabs: false

# 末尾のカンマをつける範囲
trailingComma: "es5"

# アロー関数引数のカッコ
arrowParens: "avoid"

# Markdown の文章の折り返しを勝手に変えない
# → 日本語文章だと勝手に改行されると読みにくくなるので "preserve" 推奨
proseWrap: "preserve"

# 改行コード
endOfLine: "lf"

# 対象にするファイル（必要なら調整）
overrides:
  - files: "*.md"
